[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 16.0

[font.bold]
family = "BerkeleyMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Bold Oblique"

[font.italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Oblique"

[font.normal]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"
